name: Android CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with: 
	java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew assemble --no-daemon
    - name: Depoly To Pgyer
      run: |
        curl -F "file=@${PWD}/app/build/outputs/apk/debug/app-debug.apk" \
        -F "uKey=${{secrets.PGYER_USER_KEY}}" \
        -F "_api_key=${{secrets.PGYER_API_KEY}}" \
        https://www.pgyer.com/apiv1/app/upload
